import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Squares from "@/Backgrounds/Squares/Squares";
import Particles from "@/Backgrounds/Particles/Particles";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed inset-0 z-[-1] overflow-hidden">
          <Particles particleCount={200} alphaParticles={true}  />
        </div>
      </body>
    </html>
  );
}
